services:
  # 1. База данных PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: kanban_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - kanban_network

  # 2. Бэкенд Django DRF
  backend:
    build: .
    container_name: kanban_backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - django_static:/app/static
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      # Сюда же пропиши переменные для Gmail SMTP, которые мы настраивали
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
    depends_on:
      - db
    networks:
      - kanban_network

  # 3. Фронтенд React + Nginx
  frontend:
    build: ./kanban-frontend
    container_name: kanban_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - kanban_network

volumes:
  postgres_data:
  django_static:

networks:
  kanban_network:
    driver: bridge
