# Generated by Django 6.0.3 on 2026-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_task_options_task_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
