# Generated by Django 6.0.3 on 2026-06-26 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_subtask_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['id']},
        ),
    ]
